[package]
name = "example"
version = "0.1.0"
authors = ["Richard <Richard>"]
edition = "2018"

[lib]
crate-type =["cdylib"]

[dependencies]
web_console = "0.0.0"
globals = "0.1.3" # optional: for easily getting global singletons that implement Default trait